import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import {
  MappingDraftRequestError,
  mappingDraftService,
} from '../../services/api/mappingDraftService';
import { mappingReleaseService } from '../../services/api/mappingReleaseService';
import { WorkspaceRequestError, workspaceService } from '../../services/api/workspaceService';
import { useWorkspaceStore } from '../../store/useWorkspaceStore';
import type {
  MappingAuthoringEngine,
  MappingDraft,
  MappingDraftRule,
  MappingDraftSummary,
  MappingSuggestionJob,
  UpdateMappingDraftRuleInput,
} from '../../types/mappingDraft';
import type { MappingReleaseListItem, MappingReleaseSummary } from '../../types/mappingRelease';
import type { LayoutTreeResponse, MappingExplanation } from '../../types/workspace';
import MappingFiscalProfilePanel from './MappingFiscalProfilePanel';
import MappingLayoutTreeView from './MappingLayoutTreeView';
import MappingReleaseDiffPanel from './MappingReleaseDiffPanel';
import MappingRuleReviewCard from './MappingRuleReviewCard';
import MappingTestLabPanel from './MappingTestLabPanel';
import './MappingStudioPage.css';

type RuleUpdate = Omit<UpdateMappingDraftRuleInput, 'workspaceId' | 'draftId' | 'ruleId' | 'eTag'>;

const activeJobStatuses = new Set(['queued', 'running']);

const capabilityLabels: Array<[keyof MappingExplanation['capabilities'], string]> = [
  ['execute', 'Executar'],
  ['explain', 'Explicar'],
  ['author', 'Editar'],
  ['compile', 'Compilar'],
  ['publish', 'Publicar'],
];

const releaseStatusLabels: Record<MappingReleaseSummary['status'], string> = {
  draft_compiled: 'Compilado',
  test_passed: 'Testes aprovados',
  test_failed: 'Testes reprovados',
  in_review: 'Em revisão',
  approved: 'Aprovado',
  published: 'Publicado',
  deprecated: 'Depreciado',
  archived: 'Arquivado',
};

const autoGeneratedStatusLabels: Record<
  Extract<MappingReleaseListItem, { origin: 'auto_generated' }>['status'],
  string
> = {
  ready: 'Pronto',
  generating: 'Gerando…',
  stale: 'Desatualizado',
};

const MappingReleaseCatalog = ({ workspaceId }: { workspaceId: string }) => {
  const [releases, setReleases] = useState<MappingReleaseListItem[]>([]);
  const [autoGeneratedUnavailable, setAutoGeneratedUnavailable] = useState(false);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let disposed = false;
    void mappingReleaseService
      .listReleases(workspaceId)
      .then(response => {
        if (disposed) return;
        setReleases(response.items);
        setAutoGeneratedUnavailable(response.autoGeneratedUnavailable);
        setStatus('ready');
      })
      .catch(loadError => {
        if (disposed) return;
        setReleases([]);
        setStatus('error');
        setError(
          loadError instanceof Error ? loadError.message : 'Não foi possível listar as releases.'
        );
      });

    return () => {
      disposed = true;
    };
  }, [workspaceId]);

  if (status === 'loading') {
    return (
      <section className="mapping-studio-section" aria-busy="true" aria-live="polite">
        <span className="mapping-loader" aria-hidden="true" />
        <p>Carregando releases do workspace…</p>
      </section>
    );
  }

  if (status === 'error') {
    return (
      <section className="mapping-studio-section" role="alert">
        <p className="mapping-kicker">Catálogo indisponível</p>
        <p>{error}</p>
      </section>
    );
  }

  if (releases.length === 0) {
    return (
      <section className="mapping-studio-section">
        <div className="mapping-empty-state">
          <h3>Nenhuma release ainda</h3>
          <p>Compile um draft TCL/XSLT para que ele apareça neste catálogo.</p>
        </div>
      </section>
    );
  }

  return (
    <section className="mapping-studio-section" aria-labelledby="mapping-catalog-title">
      <div className="mapping-section-heading">
        <div>
          <p className="mapping-kicker">Catálogo do workspace</p>
          <h2 id="mapping-catalog-title">Releases disponíveis</h2>
        </div>
      </div>
      {autoGeneratedUnavailable && (
        <p className="mapping-catalog-notice" role="status">
          Não foi possível carregar os mapeadores gerados automaticamente. Mostrando só as releases
          compiladas manualmente.
        </p>
      )}
      <ul className="mapping-review-list">
        {releases.map(release =>
          release.origin === 'auto_generated' ? (
            <li key={release.mapperGuid}>
              <div className="mapping-review-list__item">
                <Link
                  to={`/workspace/mapping-studio/${encodeURIComponent(release.mapperGuid)}/generated`}
                >
                  <strong>{release.mapperName}</strong>
                </Link>
                <span> — {autoGeneratedStatusLabels[release.status]}</span>
                <span
                  className="mapping-status-badge mapping-status-badge--generated"
                  title="Cobertura calculada contra a regra declarada do mapeador Sysmiddle, não contra uma execução real."
                >
                  {release.validationBasis}
                </span>
                {release.generatedCoverage?.linkPct && (
                  <span className="mapping-catalog-coverage">
                    {' '}
                    · links {release.generatedCoverage.linkPct}
                    {release.generatedCoverage.rulePct &&
                      ` · regras ${release.generatedCoverage.rulePct}`}
                  </span>
                )}
                {release.coverage && (
                  <span className="mapping-catalog-coverage">
                    {' '}
                    · cobertura {release.coverage.percent}%
                  </span>
                )}
              </div>
            </li>
          ) : (
            <li key={release.releaseId}>
              <Link to={`/workspace/mapping-studio/${encodeURIComponent(release.draftId)}/draft`}>
                <strong>{release.engine.toUpperCase()}</strong> · {release.draftId}
                <span> — {releaseStatusLabels[release.status]}</span>
              </Link>
            </li>
          )
        )}
      </ul>
    </section>
  );
};

const draftPageSize = 20;

/**
 * Catálogo de drafts TCL/XSLT do workspace (issue #198, parte 1). Fica como seção própria na
 * entrada do Mapping Studio, ao lado do catálogo de releases — draft e release são conceitos
 * distintos (draft não tem status de governança). Clicar num item navega para a mesma rota de
 * revisão de draft já usada pelo catálogo de releases (`/workspace/mapping-studio/:draftId/draft`).
 */
const MappingDraftCatalog = ({ workspaceId }: { workspaceId: string }) => {
  const [drafts, setDrafts] = useState<MappingDraftSummary[]>([]);
  const [page, setPage] = useState(1);
  const [totalCount, setTotalCount] = useState(0);
  const [engineFilter, setEngineFilter] = useState<MappingAuthoringEngine | ''>('');
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [error, setError] = useState<string | null>(null);
  const requestKey = `${workspaceId}:${page}:${engineFilter}`;
  const [loadedKey, setLoadedKey] = useState<string | null>(null);
  if (requestKey !== loadedKey && status !== 'loading') {
    setStatus('loading');
  }

  useEffect(() => {
    let disposed = false;
    void mappingDraftService
      .listDrafts(workspaceId, page, draftPageSize, engineFilter || undefined)
      .then(response => {
        if (disposed) return;
        setDrafts(response.items);
        setTotalCount(response.totalCount);
        setStatus('ready');
        setLoadedKey(requestKey);
      })
      .catch(loadError => {
        if (disposed) return;
        setDrafts([]);
        setStatus('error');
        setLoadedKey(requestKey);
        setError(
          loadError instanceof Error ? loadError.message : 'Não foi possível listar os drafts.'
        );
      });

    return () => {
      disposed = true;
    };
  }, [workspaceId, page, engineFilter, requestKey]);

  const totalPages = Math.max(1, Math.ceil(totalCount / draftPageSize));

  return (
    <section className="mapping-studio-section" aria-labelledby="mapping-draft-catalog-title">
      <div className="mapping-section-heading">
        <div>
          <p className="mapping-kicker">Catálogo do workspace</p>
          <h2 id="mapping-draft-catalog-title">Drafts em revisão</h2>
        </div>
        <label>
          Motor
          <select
            value={engineFilter}
            onChange={event => {
              setPage(1);
              setEngineFilter(event.target.value as MappingAuthoringEngine | '');
            }}
          >
            <option value="">Todos</option>
            <option value="tcl">TCL</option>
            <option value="xslt">XSLT</option>
          </select>
        </label>
      </div>

      {status === 'loading' && (
        <div aria-busy="true" aria-live="polite">
          <span className="mapping-loader" aria-hidden="true" />
          <p>Carregando drafts do workspace…</p>
        </div>
      )}

      {status === 'error' && (
        <div role="alert">
          <p className="mapping-kicker">Catálogo indisponível</p>
          <p>{error}</p>
        </div>
      )}

      {status === 'ready' && drafts.length === 0 && (
        <div className="mapping-empty-state">
          <h3>Nenhum draft ainda</h3>
          <p>Crie um draft a partir de um pacote de mapeamento para que ele apareça aqui.</p>
        </div>
      )}

      {status === 'ready' && drafts.length > 0 && (
        <>
          <ul className="mapping-review-list">
            {drafts.map(draft => (
              <li key={draft.draftId}>
                <Link to={`/workspace/mapping-studio/${encodeURIComponent(draft.draftId)}/draft`}>
                  <strong>{draft.engine.toUpperCase()}</strong> · {draft.draftId}
                  <span> — {draft.rulesCount} regra(s)</span>
                  {draft.fiscalProfile && (
                    <span> · {draft.fiscalProfile.documentType.toUpperCase()}</span>
                  )}
                </Link>
              </li>
            ))}
          </ul>
          {totalPages > 1 && (
            <div className="mapping-rule-actions">
              <button
                type="button"
                className="mapping-button"
                disabled={page <= 1}
                onClick={() => setPage(current => Math.max(1, current - 1))}
              >
                Anterior
              </button>
              <span>
                Página {page} de {totalPages}
              </span>
              <button
                type="button"
                className="mapping-button"
                disabled={page >= totalPages}
                onClick={() => setPage(current => Math.min(totalPages, current + 1))}
              >
                Próxima
              </button>
            </div>
          )}
        </>
      )}
    </section>
  );
};

const MappingStudioEntry = () => {
  const navigate = useNavigate();
  const { activeWorkspaceId } = useWorkspaceStore();
  const [mappingId, setMappingId] = useState('');
  const [version, setVersion] = useState<'draft' | 'current'>('draft');

  return (
    <main className="mapping-studio-page mapping-studio-page--entry">
      <section className="mapping-studio-entry" aria-labelledby="mapping-entry-title">
        <p className="mapping-kicker">Mapping Studio fiscal</p>
        <h1 id="mapping-entry-title">Compreenda e revise uma transformação</h1>
        <p>
          Abra um draft TCL/XSLT para revisar propostas da IA ou um mapper Sysmiddle existente em
          modo estritamente explicativo.
        </p>
        <form
          onSubmit={event => {
            event.preventDefault();
            if (mappingId.trim()) {
              navigate(
                `/workspace/mapping-studio/${encodeURIComponent(mappingId.trim())}/${version}`
              );
            }
          }}
        >
          <label>
            Identificador do draft ou mapping
            <input
              value={mappingId}
              onChange={event => setMappingId(event.target.value)}
              placeholder="GUID do MappingDraft ou MapperGuid"
              required
            />
          </label>
          <label>
            Tipo de leitura
            <select
              value={version}
              onChange={event => setVersion(event.target.value as 'draft' | 'current')}
            >
              <option value="draft">Draft TCL/XSLT em revisão</option>
              <option value="current">Sysmiddle publicado (somente leitura)</option>
            </select>
          </label>
          <button type="submit" className="mapping-button mapping-button--primary">
            Abrir mapping
          </button>
        </form>
        <aside>
          Mappers Sysmiddle publicados ainda não têm catálogo de descoberta — abra-os pelo
          identificador acima. Releases de draft TCL/XSLT já podem ser listadas abaixo.
        </aside>
        <Link to="/workspace">Voltar ao workspace</Link>
      </section>
      {activeWorkspaceId && (
        <MappingReleaseCatalog
          key={`releases:${activeWorkspaceId}`}
          workspaceId={activeWorkspaceId}
        />
      )}
      {activeWorkspaceId && (
        <MappingDraftCatalog key={`drafts:${activeWorkspaceId}`} workspaceId={activeWorkspaceId} />
      )}
    </main>
  );
};

const fetchMappingData = async (workspaceId: string, mappingId: string, version: string) => {
  const explanation = await workspaceService.getMappingExplanation(workspaceId, mappingId, version);
  const canLoadDraft =
    explanation.capabilities.author && explanation.engine !== 'sysmiddle' && version === 'draft';
  const draft = canLoadDraft ? await mappingDraftService.getDraft(workspaceId, mappingId) : null;
  return { explanation, draft };
};

const MappingStudioDetail = ({ mappingId, version }: { mappingId: string; version: string }) => {
  const { status, activeWorkspaceId, workspaces } = useWorkspaceStore();
  const activeWorkspaceRole = workspaces.find(
    workspace => workspace.workspaceId === activeWorkspaceId
  )?.role;
  const [explanation, setExplanation] = useState<MappingExplanation | null>(null);
  const [draft, setDraft] = useState<MappingDraft | null>(null);
  const [job, setJob] = useState<MappingSuggestionJob | null>(null);
  const [loading, setLoading] = useState(true);
  const [busyRuleId, setBusyRuleId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [layoutTree, setLayoutTree] = useState<LayoutTreeResponse | null>(null);
  const [layoutTreeStatus, setLayoutTreeStatus] = useState<'loading' | 'ready' | 'error'>(
    'loading'
  );
  const [layoutTreeError, setLayoutTreeError] = useState<string | null>(null);

  const loadMapping = useCallback(async () => {
    if (!activeWorkspaceId) return;
    try {
      const next = await fetchMappingData(activeWorkspaceId, mappingId, version);
      setError(null);
      setExplanation(next.explanation);
      setDraft(next.draft);
    } catch (loadError) {
      setExplanation(null);
      setDraft(null);
      setError(
        loadError instanceof Error ? loadError.message : 'Não foi possível abrir este mapping.'
      );
    } finally {
      setLoading(false);
    }
  }, [activeWorkspaceId, mappingId, version]);

  useEffect(() => {
    if (status !== 'ready' || !activeWorkspaceId) return;

    let disposed = false;
    void fetchMappingData(activeWorkspaceId, mappingId, version)
      .then(next => {
        if (disposed) return;
        setError(null);
        setExplanation(next.explanation);
        setDraft(next.draft);
      })
      .catch(loadError => {
        if (disposed) return;
        setExplanation(null);
        setDraft(null);
        setError(
          loadError instanceof Error ? loadError.message : 'Não foi possível abrir este mapping.'
        );
      })
      .finally(() => {
        if (!disposed) setLoading(false);
      });

    return () => {
      disposed = true;
    };
  }, [activeWorkspaceId, mappingId, status, version]);

  useEffect(() => {
    if (status !== 'ready' || !activeWorkspaceId) return;

    let disposed = false;
    void workspaceService
      .getMappingLayoutTree(activeWorkspaceId, mappingId)
      .then(response => {
        if (disposed) return;
        setLayoutTree(response);
        setLayoutTreeError(null);
        setLayoutTreeStatus('ready');
      })
      .catch(loadError => {
        if (disposed) return;
        setLayoutTree(null);
        setLayoutTreeStatus('error');
        setLayoutTreeError(
          loadError instanceof WorkspaceRequestError || loadError instanceof Error
            ? loadError.message
            : 'Não foi possível carregar a árvore deste mapping.'
        );
      });

    return () => {
      disposed = true;
    };
  }, [activeWorkspaceId, mappingId, status]);

  useEffect(() => {
    if (!job || !draft || !activeWorkspaceId || !activeJobStatuses.has(job.status)) return;

    let disposed = false;
    const timer = window.setTimeout(() => {
      void mappingDraftService
        .getSuggestion(activeWorkspaceId, draft.draftId, job.jobId)
        .then(nextJob => {
          if (disposed) return;
          setJob(nextJob);
          if (nextJob.status === 'completed') {
            void loadMapping();
          }
        })
        .catch(jobError => {
          if (!disposed) {
            setError(
              jobError instanceof Error
                ? jobError.message
                : 'Não foi possível consultar o job de sugestão.'
            );
          }
        });
    }, 1200);

    return () => {
      disposed = true;
      window.clearTimeout(timer);
    };
  }, [activeWorkspaceId, draft, job, loadMapping]);

  const handleRuleUpdate = async (rule: MappingDraftRule, update: RuleUpdate) => {
    if (!activeWorkspaceId || !draft || !explanation?.capabilities.author) {
      throw new Error('A autoria não está disponível para este mapping.');
    }

    setBusyRuleId(rule.ruleId);
    try {
      const updated = await mappingDraftService.updateRule({
        workspaceId: activeWorkspaceId,
        draftId: draft.draftId,
        ruleId: rule.ruleId,
        eTag: rule.eTag,
        ...update,
      });
      setDraft(current =>
        current
          ? {
              ...current,
              rules: current.rules.map(item => (item.ruleId === updated.ruleId ? updated : item)),
            }
          : current
      );
      const refreshedExplanation = await workspaceService.getMappingExplanation(
        activeWorkspaceId,
        mappingId,
        version
      );
      setExplanation(refreshedExplanation);
    } catch (updateError) {
      if (updateError instanceof MappingDraftRequestError && updateError.currentRule) {
        const currentRule = updateError.currentRule;
        setDraft(current =>
          current
            ? {
                ...current,
                rules: current.rules.map(item =>
                  item.ruleId === currentRule.ruleId ? currentRule : item
                ),
              }
            : current
        );
      }
      throw updateError;
    } finally {
      setBusyRuleId(null);
    }
  };

  const startSuggestion = async () => {
    if (!activeWorkspaceId || !draft) return;
    setError(null);
    try {
      setJob(await mappingDraftService.createSuggestion(activeWorkspaceId, draft.draftId));
    } catch (suggestionError) {
      setError(
        suggestionError instanceof Error
          ? suggestionError.message
          : 'Não foi possível iniciar as sugestões.'
      );
    }
  };

  const cancelSuggestion = async () => {
    if (!activeWorkspaceId || !draft || !job) return;
    try {
      await mappingDraftService.cancelSuggestion(activeWorkspaceId, draft.draftId, job.jobId);
      setJob({ ...job, status: 'canceled' });
    } catch (cancelError) {
      setError(
        cancelError instanceof Error ? cancelError.message : 'Não foi possível cancelar o job.'
      );
    }
  };

  if (status === 'idle' || status === 'loading' || loading) {
    return (
      <main
        className="mapping-studio-page mapping-studio-page--state"
        aria-busy="true"
        aria-live="polite"
      >
        <span className="mapping-loader" aria-hidden="true" />
        <h1>Abrindo o Mapping Studio…</h1>
      </main>
    );
  }

  if (error && !explanation) {
    return (
      <main className="mapping-studio-page mapping-studio-page--state">
        <section role="alert">
          <p className="mapping-kicker">Mapping indisponível</p>
          <h1>Não foi possível abrir esta transformação</h1>
          <p>{error}</p>
          <div className="mapping-rule-actions">
            <button
              type="button"
              className="mapping-button mapping-button--primary"
              onClick={() => void loadMapping()}
            >
              Tentar novamente
            </button>
            <Link to="/workspace/mapping-studio">Abrir outro mapping</Link>
          </div>
        </section>
      </main>
    );
  }

  if (!explanation) return null;

  const readOnly = explanation.engine === 'sysmiddle' || !explanation.capabilities.author;
  const effectiveCapabilities =
    explanation.engine === 'sysmiddle'
      ? {
          ...explanation.capabilities,
          author: false,
          compile: false,
          publish: false,
        }
      : explanation.capabilities;
  const activeJob = job && activeJobStatuses.has(job.status);

  return (
    <main className="mapping-studio-page">
      <nav className="mapping-breadcrumb" aria-label="Navegação do Mapping Studio">
        <Link to="/workspace">Workspace</Link>
        <span aria-hidden="true">/</span>
        <Link to="/workspace/mapping-studio">Mapping Studio</Link>
        <span aria-hidden="true">/</span>
        <span aria-current="page">{mappingId}</span>
      </nav>

      <header className="mapping-studio-hero">
        <div>
          <p className="mapping-kicker">
            {explanation.engine.toUpperCase()} · {explanation.version}
          </p>
          <h1>{explanation.description || 'Explicação da transformação'}</h1>
          <p className="mapping-id-copy">Mapping {explanation.mappingId}</p>
        </div>
        <span className={`mapping-mode-badge ${readOnly ? 'mapping-mode-badge--readonly' : ''}`}>
          {readOnly ? 'Somente leitura' : 'Revisão humana habilitada'}
        </span>
      </header>

      {error && (
        <p className="mapping-page-error" role="alert">
          {error}
        </p>
      )}

      <section className="mapping-capability-grid" aria-label="Capacidades deste motor">
        {capabilityLabels.map(([capability, label]) => (
          <article key={capability} data-enabled={effectiveCapabilities[capability]}>
            <span aria-hidden="true">{effectiveCapabilities[capability] ? '✓' : '—'}</span>
            <div>
              <strong>{label}</strong>
              <small>{effectiveCapabilities[capability] ? 'Disponível' : 'Indisponível'}</small>
            </div>
          </article>
        ))}
      </section>

      {(explanation.sourceSchema || explanation.targetSchema) && (
        <section className="mapping-schema-flow" aria-label="Fluxo de schemas">
          <article>
            <span>Origem</span>
            <strong>{explanation.sourceSchema?.description || 'Schema de origem'}</strong>
            <code>{explanation.sourceSchema?.layoutGuid || 'GUID não informado'}</code>
          </article>
          <span className="mapping-schema-flow__arrow" aria-hidden="true">
            →
          </span>
          <article>
            <span>Destino</span>
            <strong>{explanation.targetSchema?.description || 'Schema de destino'}</strong>
            <code>{explanation.targetSchema?.layoutGuid || 'GUID não informado'}</code>
          </article>
        </section>
      )}

      {explanation.limitations.length > 0 && (
        <aside className="mapping-limitations">
          <strong>Limites conhecidos desta explicação</strong>
          <ul>
            {explanation.limitations.map(item => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </aside>
      )}

      {draft && effectiveCapabilities.author && activeWorkspaceId && (
        <MappingFiscalProfilePanel
          workspaceId={activeWorkspaceId}
          draft={draft}
          onDraftChange={setDraft}
        />
      )}

      {draft && effectiveCapabilities.author && (
        <section className="mapping-studio-section" aria-labelledby="mapping-review-title">
          <div className="mapping-section-heading">
            <div>
              <p className="mapping-kicker">Humano no controle</p>
              <h2 id="mapping-review-title">Revisão das propostas</h2>
              <p>
                Cada decisão usa ETag/If-Match. Uma alteração concorrente é recarregada em vez de
                sobrescrita.
              </p>
            </div>
            <div className="mapping-suggestion-actions">
              <button
                type="button"
                className="mapping-button mapping-button--primary"
                disabled={Boolean(activeJob)}
                onClick={() => void startSuggestion()}
              >
                {activeJob ? 'IA analisando…' : 'Gerar sugestões'}
              </button>
              {activeJob && (
                <button
                  type="button"
                  className="mapping-button"
                  onClick={() => void cancelSuggestion()}
                >
                  Cancelar job
                </button>
              )}
            </div>
          </div>

          {job && (
            <p className="mapping-job-status" role="status">
              Job {job.jobId}: <strong>{job.status}</strong>
              {job.rulesCreated !== undefined ? ` · ${job.rulesCreated} regra(s) criada(s)` : ''}
              {job.error ? ` · ${job.error}` : ''}
            </p>
          )}

          {draft.rules.length === 0 ? (
            <div className="mapping-empty-state">
              <h3>Nenhuma proposta ainda</h3>
              <p>Inicie o job de sugestões para analisar as evidências da revisão vinculada.</p>
            </div>
          ) : (
            <div className="mapping-review-list">
              {activeWorkspaceId &&
                draft.rules.map(rule => (
                  <MappingRuleReviewCard
                    key={rule.ruleId}
                    workspaceId={activeWorkspaceId}
                    draftId={draft.draftId}
                    rule={rule}
                    busy={busyRuleId === rule.ruleId}
                    onUpdate={handleRuleUpdate}
                  />
                ))}
            </div>
          )}
        </section>
      )}

      {draft && effectiveCapabilities.author && activeWorkspaceId && activeWorkspaceRole && (
        <MappingTestLabPanel
          workspaceId={activeWorkspaceId}
          draft={draft}
          compileEnabled={effectiveCapabilities.compile}
          executeEnabled={effectiveCapabilities.execute}
          workspaceRole={activeWorkspaceRole}
        />
      )}

      {draft && effectiveCapabilities.author && activeWorkspaceId && (
        <MappingReleaseDiffPanel workspaceId={activeWorkspaceId} draftId={draft.draftId} />
      )}

      <section className="mapping-studio-section" aria-labelledby="mapping-layout-tree-title">
        <div className="mapping-section-heading">
          <div>
            <p className="mapping-kicker">Árvore dupla · estilo Connect-Us</p>
            <h2 id="mapping-layout-tree-title">Mapeador</h2>
            <p>
              Hierarquia real do layout de origem e destino, com regras inline vinculadas por GUID
              (LayoutParserApi#425). {explanation.opaqueRuleCount} regra(s) opaca(s) no contrato
              canônico. Selecione um nó com badge de regra e use “Ver regra” para o detalhe
              completo, incluindo lógica condicional/DSL.
            </p>
          </div>
        </div>

        {layoutTreeStatus === 'loading' && (
          <div className="mapping-studio-section" aria-busy="true" aria-live="polite">
            <span className="mapping-loader" aria-hidden="true" />
            <p>Carregando árvore do mapping…</p>
          </div>
        )}

        {layoutTreeStatus === 'error' && (
          <div role="alert">
            <p className="mapping-kicker">Árvore indisponível</p>
            <p>{layoutTreeError}</p>
          </div>
        )}

        {layoutTreeStatus === 'ready' && layoutTree && (
          <MappingLayoutTreeView
            source={layoutTree.source}
            target={layoutTree.target}
            rules={layoutTree.rules}
            limitations={layoutTree.limitations}
            explanationRules={explanation.rules}
          />
        )}
      </section>
    </main>
  );
};

const MappingStudioPage = () => {
  const { mappingId, version } = useParams();
  if (!mappingId || !version) {
    return <MappingStudioEntry />;
  }
  return (
    <MappingStudioDetail key={`${mappingId}:${version}`} mappingId={mappingId} version={version} />
  );
};

export default MappingStudioPage;
