import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { mappingDraftService } from '../../services/api/mappingDraftService';
import { mappingReleaseService } from '../../services/api/mappingReleaseService';
import { workspaceService } from '../../services/api/workspaceService';
import { useWorkspaceStore } from '../../store/useWorkspaceStore';
import MappingStudioPage from './MappingStudioPage';

vi.mock('../../services/api/workspaceService', async importOriginal => {
  const original = await importOriginal<typeof import('../../services/api/workspaceService')>();
  return {
    WorkspaceRequestError: original.WorkspaceRequestError,
    workspaceService: {
      getMappingExplanation: vi.fn(),
      getMappingLayoutTree: vi.fn(),
    },
  };
});

vi.mock('../../services/api/mappingReleaseService', () => ({
  mappingReleaseService: { listReleases: vi.fn() },
}));

vi.mock('../../services/api/mappingDraftService', async importOriginal => {
  const original = await importOriginal<typeof import('../../services/api/mappingDraftService')>();
  return {
    ...original,
    mappingDraftService: {
      getDraft: vi.fn(),
      createSuggestion: vi.fn(),
      getSuggestion: vi.fn(),
      cancelSuggestion: vi.fn(),
      updateRule: vi.fn(),
      listDrafts: vi.fn(),
    },
  };
});

const capabilities = {
  execute: true,
  explain: true,
  author: false,
  compile: false,
  publish: false,
};

const sysmiddleExplanation = {
  mappingId: 'mapper-1',
  version: 'current',
  engine: 'sysmiddle' as const,
  capabilities,
  sourceSchema: { layoutGuid: 'source-guid', description: 'TXT FIAT' },
  targetSchema: { layoutGuid: 'target-guid', description: 'NF-e 4.00' },
  rules: [
    {
      ruleId: 'rule-1',
      sourceRefs: ['I.CNPJ'],
      targetRefs: ['T.emit.CNPJ'],
      condition: null,
      operations: ['copy'],
      cardinality: '1:1',
      evidence: [{ kind: 'sysmiddle-link-mapping', reference: 'CNPJ emitente' }],
      humanDescription: 'Copia o CNPJ do emitente para o XML.',
      technicalDetail: null,
      supportLevel: 'authoritative' as const,
    },
  ],
  description: 'Mapper atual da NF-e',
  limitations: [],
  opaqueRuleCount: 0,
};

const draftRule = {
  ruleId: 'rule-1',
  draftId: 'draft-1',
  sourceRefs: ['layout://LINHA004/CNPJ'],
  targetRefs: ['xsd:///NFe/infNFe/emit/CNPJ'],
  operation: 'copy',
  conditions: '[]',
  transformations: '["trim"]',
  cardinality: '1:1',
  evidence: [{ kind: 'xsd', reference: '/NFe/infNFe/emit/CNPJ' }],
  confidence: 'high',
  status: 'proposed' as const,
  questions: [],
  createdAt: '2026-08-31T19:00:00Z',
  eTag: 'AAAAAAAAAAE=',
};

const draft = {
  draftId: 'draft-1',
  workspaceId: 'workspace-1',
  packageId: 'package-1',
  revisionId: 'revision-1',
  engine: 'tcl' as const,
  createdAt: '2026-08-31T19:00:00Z',
  rules: [draftRule],
  fiscalProfile: null,
  resolvedXsd: null,
};

const tclExplanation = {
  ...sysmiddleExplanation,
  mappingId: 'draft-1',
  version: 'draft',
  engine: 'tcl' as const,
  capabilities: { ...capabilities, execute: false, author: true },
  sourceSchema: null,
  targetSchema: null,
  description: null,
};

function renderRoute(path: string) {
  return render(
    <MemoryRouter initialEntries={[path]}>
      <Routes>
        <Route path="workspace/mapping-studio" element={<MappingStudioPage />} />
        <Route
          path="workspace/mapping-studio/:mappingId/:version"
          element={<MappingStudioPage />}
        />
      </Routes>
    </MemoryRouter>
  );
}

describe('MappingStudioPage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    window.localStorage.clear();
    vi.mocked(mappingReleaseService.listReleases).mockResolvedValue({
      items: [],
      page: 1,
      pageSize: 20,
      totalCount: 0,
      autoGeneratedUnavailable: false,
    });
    vi.mocked(workspaceService.getMappingLayoutTree).mockResolvedValue({
      source: { roots: [] },
      target: { roots: [] },
      rules: [],
      limitations: [],
    });
    vi.mocked(mappingDraftService.listDrafts).mockResolvedValue({
      items: [],
      page: 1,
      pageSize: 20,
      totalCount: 0,
    });
    useWorkspaceStore.setState({
      status: 'ready',
      activeWorkspaceId: 'workspace-1',
      workspaces: [
        {
          workspaceId: 'workspace-1',
          name: 'Workspace fiscal',
          kind: 'personal',
          role: 'owner',
          createdAt: '2026-08-31T12:00:00Z',
        },
      ],
      error: null,
    });
  });

  it('abre um mapping a partir da entrada sem persistir o identificador', async () => {
    vi.mocked(workspaceService.getMappingExplanation).mockResolvedValue(sysmiddleExplanation);
    renderRoute('/workspace/mapping-studio');

    fireEvent.change(screen.getByLabelText('Identificador do draft ou mapping'), {
      target: { value: 'mapper-1' },
    });
    fireEvent.change(screen.getByLabelText('Tipo de leitura'), { target: { value: 'current' } });
    fireEvent.click(screen.getByRole('button', { name: 'Abrir mapping' }));

    expect(await screen.findByRole('heading', { name: 'Mapper atual da NF-e' })).toBeVisible();
    expect(window.localStorage).toHaveLength(0);
  });

  it('lista releases do workspace ativo e linka para o draft correspondente (issue #198)', async () => {
    vi.mocked(mappingReleaseService.listReleases).mockResolvedValue({
      items: [
        {
          origin: 'draft_compile',
          releaseId: 'release-1',
          workspaceId: 'workspace-1',
          draftId: 'draft-1',
          engine: 'xslt',
          status: 'test_passed',
          environment: 'development',
          approvedByUserId: null,
          approvedAt: null,
          approvalJustification: null,
          publishedByUserId: null,
          publishedAt: null,
          previousPublishedReleaseId: null,
          correlationId: 'correlation-1',
          eTag: 'AAAAAAAAAAE=',
        },
      ],
      page: 1,
      pageSize: 20,
      totalCount: 1,
      autoGeneratedUnavailable: false,
    });

    renderRoute('/workspace/mapping-studio');

    const link = await screen.findByRole('link', { name: /XSLT.*draft-1.*Testes aprovados/s });
    expect(link).toHaveAttribute('href', '/workspace/mapping-studio/draft-1/draft');
    expect(mappingReleaseService.listReleases).toHaveBeenCalledWith('workspace-1');
  });

  it('mostra estado vazio do catálogo quando o workspace não tem releases', async () => {
    renderRoute('/workspace/mapping-studio');
    expect(await screen.findByText('Nenhuma release ainda')).toBeVisible();
  });

  it('lista mapeadores gerados automaticamente sem ações de governança e com selo de validationBasis', async () => {
    vi.mocked(mappingReleaseService.listReleases).mockResolvedValue({
      items: [
        {
          origin: 'auto_generated',
          mapperGuid: 'mapper-guid-1',
          mapperName: 'MAP_CNHI_MQSERIES_SEND_ENV_TXT_XML_NFE',
          status: 'ready',
          validationBasis: 'declared_dsl',
          coverage: null,
          generatedCoverage: {
            generatorVersion: '2',
            compiles: true,
            compileError: null,
            linksCovered: 244,
            linksTotal: 244,
            linkPct: '100%',
            rulesCovered: 46,
            rulesTotal: 47,
            rulePct: '97.9%',
            provenanceEntries: 317,
            linkMappingsSemFolha: 0,
            limitations: [],
          },
          generatedAt: '2026-09-20T12:00:00Z',
          correlationId: 'correlation-2',
          detailUrl: '/api/workspaces/workspace-1/mappings/mapper-guid-1/generated-transformation',
        },
      ],
      page: 1,
      pageSize: 20,
      totalCount: 1,
      autoGeneratedUnavailable: false,
    });

    renderRoute('/workspace/mapping-studio');

    expect(await screen.findByText('MAP_CNHI_MQSERIES_SEND_ENV_TXT_XML_NFE')).toBeVisible();
    expect(screen.getByText('declared_dsl')).toBeVisible();
    expect(screen.getByText(/links 100% · regras 97.9%/)).toBeVisible();
    expect(
      screen.queryByRole('link', { name: /MAP_CNHI_MQSERIES_SEND_ENV_TXT_XML_NFE/ })
    ).not.toBeInTheDocument();
  });

  it('mostra aviso discreto quando a leitura dos gerados automaticamente falha', async () => {
    vi.mocked(mappingReleaseService.listReleases).mockResolvedValue({
      items: [
        {
          origin: 'draft_compile',
          releaseId: 'release-1',
          workspaceId: 'workspace-1',
          draftId: 'draft-1',
          engine: 'xslt',
          status: 'test_passed',
          environment: 'development',
          approvedByUserId: null,
          approvedAt: null,
          approvalJustification: null,
          publishedByUserId: null,
          publishedAt: null,
          previousPublishedReleaseId: null,
          correlationId: 'correlation-1',
          eTag: 'AAAAAAAAAAE=',
        },
      ],
      page: 1,
      pageSize: 20,
      totalCount: 1,
      autoGeneratedUnavailable: true,
    });

    renderRoute('/workspace/mapping-studio');

    expect(
      await screen.findByText(/Não foi possível carregar os mapeadores gerados automaticamente/)
    ).toBeVisible();
  });

  it('lista drafts do workspace ativo e linka para a rota de revisão (issue #198)', async () => {
    vi.mocked(mappingDraftService.listDrafts).mockResolvedValue({
      items: [
        {
          draftId: 'draft-2',
          workspaceId: 'workspace-1',
          packageId: 'package-1',
          revisionId: 'revision-1',
          engine: 'tcl',
          createdAt: '2026-09-22T10:00:00Z',
          rulesCount: 3,
          fiscalProfile: null,
        },
      ],
      page: 1,
      pageSize: 20,
      totalCount: 1,
    });

    renderRoute('/workspace/mapping-studio');

    const link = await screen.findByRole('link', { name: /TCL.*draft-2.*3 regra\(s\)/s });
    expect(link).toHaveAttribute('href', '/workspace/mapping-studio/draft-2/draft');
    expect(mappingDraftService.listDrafts).toHaveBeenCalledWith('workspace-1', 1, 20, undefined);
  });

  it('mostra estado vazio do catálogo de drafts quando o workspace não tem drafts', async () => {
    renderRoute('/workspace/mapping-studio');
    expect(await screen.findByText('Nenhum draft ainda')).toBeVisible();
  });

  it('filtra drafts por engine e reinicia a paginação', async () => {
    renderRoute('/workspace/mapping-studio');

    await screen.findByText('Nenhum draft ainda');

    fireEvent.change(screen.getByLabelText('Motor'), { target: { value: 'xslt' } });

    await waitFor(() => {
      expect(mappingDraftService.listDrafts).toHaveBeenCalledWith('workspace-1', 1, 20, 'xslt');
    });
  });

  it('renderiza Sysmiddle somente leitura sem controles de autoria', async () => {
    vi.mocked(workspaceService.getMappingExplanation).mockResolvedValue(sysmiddleExplanation);

    renderRoute('/workspace/mapping-studio/mapper-1/current');

    expect(await screen.findByRole('heading', { name: 'Mapper atual da NF-e' })).toBeVisible();
    expect(screen.getByText('Somente leitura')).toBeVisible();
    expect(screen.queryByRole('button', { name: 'Aceitar proposta' })).not.toBeInTheDocument();
    expect(mappingDraftService.getDraft).not.toHaveBeenCalled();
  });

  it('mantém Sysmiddle sem autoria mesmo se o service for adulterado em memória', async () => {
    vi.mocked(workspaceService.getMappingExplanation).mockResolvedValue({
      ...sysmiddleExplanation,
      capabilities: {
        execute: true,
        explain: true,
        author: true,
        compile: true,
        publish: true,
      },
    });

    renderRoute('/workspace/mapping-studio/mapper-1/current');

    expect(await screen.findByText('Somente leitura')).toBeVisible();
    expect(screen.queryByRole('button', { name: 'Gerar sugestões' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'Compilar snapshot' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /publicar/i })).not.toBeInTheDocument();
    expect(screen.getByText('Editar').closest('article')).toHaveAttribute('data-enabled', 'false');
    expect(screen.getByText('Compilar').closest('article')).toHaveAttribute(
      'data-enabled',
      'false'
    );
    expect(screen.getByText('Publicar').closest('article')).toHaveAttribute(
      'data-enabled',
      'false'
    );
    expect(mappingDraftService.getDraft).not.toHaveBeenCalled();
  });

  it('revisa uma proposta TCL e atualiza a explicação após o ETag ser aceito', async () => {
    vi.mocked(workspaceService.getMappingExplanation).mockResolvedValue(tclExplanation);
    vi.mocked(mappingDraftService.getDraft).mockResolvedValue(draft);
    vi.mocked(mappingDraftService.updateRule).mockResolvedValue({
      ...draftRule,
      status: 'accepted',
      eTag: 'AAAAAAAAAAI=',
    });

    renderRoute('/workspace/mapping-studio/draft-1/draft');

    const accept = await screen.findByRole('button', { name: 'Aceitar proposta' });
    fireEvent.click(accept);

    await waitFor(() =>
      expect(mappingDraftService.updateRule).toHaveBeenCalledWith({
        workspaceId: 'workspace-1',
        draftId: 'draft-1',
        ruleId: 'rule-1',
        eTag: 'AAAAAAAAAAE=',
        status: 'accepted',
      })
    );
    expect(await screen.findByText('Aceita')).toBeVisible();
    expect(workspaceService.getMappingExplanation).toHaveBeenCalledTimes(2);
  });
});
